//List<String> title = [
//  '555 Timer Monostable Circuit Calculator':'',
//  'Antenna Downtilt and Coverage Calculator':'',
//  'Asymmetric Stripline Impedance Calculator':'',
//  'Balanced Attenuator Calculator':'',
//  'Bandpass Filter Calculator':'',
//  'Bridged-Tee Attenuator Calculator':'',
//  'Broadside Coupled Stripline Impedance Calculator':'',
//  'Broadside Coupled Trace Inductance Calculator':'',
//  'Capacitance Calculator':'',
//  'Capacitance, Reactance, and Admittance Calculator':'',
//  'Capacitor Charge and Time Constant Calculator':'',
//  'Capacitor Impedance Calculator':'',
//  'Coax Impedance Calculator':'',
//  'Coax Inductance Calculator':'',
//  'Coil Inductance Calculator':'',
//  'Convert MCD to Lumens':'',
//  'Edge Coupled Microstrip Impedance Calculator':'',
//  'Edge Coupled Stripline Impedance Calculator':'',
//  'Edge Coupled Trace Inductance Calculator':'',
//  'EIRP Calculator':'',
//  'Embedded Microstrip Impedance Calculator':'',
//  'Flyback Switch Mode Regulator Calculator':'',
//  'Free Space Path Loss Calculator':'',
//  'Friis Transmission Calculator':'',
//  'Heat Sink Calculator':'',
//  'Inductance, Reactance, and Admittance Calculator':'',
//  'Inverting Op-Amp Resistor Calculator':'',
//  'L-Match Impedance Matching Circuits':'',
//  'LED Resistor Calculator':'',
//  'Link Budget Calculator':'',
//  'Microstrip Crosstalk Calculator':'',
//  'Microstrip Impedance Calculator':'',
//  'Microstrip Inductance Calculator':'',
//  'Microstrip Max Current Calculator':'',
//  'Microstrip Patch Antenna Calculator':'',
//  'Microstrip Trace Width Calculator':'',
//  'Microstrip Wavelength Calculator':'',
//  'N-Way Power Divider Calculator':'',
//  'Noise Figure and Noise Temperature Calculator':'',
//  'Noise Figure Calculator':'',
//  'Non-Inverting Op-Amp Resistor Calculator':'',
//  'Ohm’s Law Calculator':'',
//  'Op-Amp Voltage and Gain Calculator':'',
//  'Parallel Resistance Calculator':'',
//  'Parallel Wire Inductance Calculator':'',
//  'Peak to Peak Voltage Calculator (VP-P)':'',
//  'Peak Voltage Calculator':'',
//  'Pi Attenuator Calculator':'',
//  'Pi-Match Impedance Matching Calculator':'',
//  'Power Added Efficiency Calculator':'',
//  'Power Density Calculator':'',
//  'Radar Maximum Range Calculator':'',
//  'Rectangle Loop Inductance Calculator':'',
//  'Reflection Attenuator Calculator':'',
//  'Resistance Calculator':'',
//  'Resistor Color Code Calculator':'',
//  'RF Power Conversion Calculator':'',
//  'RF Power Ratio Conversion Calculator':'',
//  'RMS Voltage Calculator':'',
//  'Skin Depth Calculator':'',
//  'Stepper Motor Calculator':'',
//  'Stripline Crosstalk Calculator':'',
//  'Stripline Max Current Calculator':'',
//  'Stripline Trace Width Calculator':'',
//  'Symmetric Stripline Impedance Calculator':'',
//  'T-Match Impedance Matching Circuits':'',
//  'T-Pad Attenuator Calculator':'',
//  'Tank Circuit Resonance Calculator':'',
//  'Temperature Converter':'',
//  'Torque Conversion Calculator':'',
//  'Trace Resistance Calculator':'',
//  'Twisted-Pair Impedance Calculator':'',
//  'Unit Conversion Calculator':'',
//  'Voltage Divider Calculator':'',
//  'VSWR  Return Loss Calculator':'',
//  'Waveguide Calculator (Circular)':'',
//  'Waveguide Calculator (Rectangular)':'',
//  'Wavelength (TEM) Calculator':'',
//  'Wire Loop Inductance Calculator':'',
//  'Wire Microstrip Impedance Calculator':'',
//  'Wire Over Plane Inductance Calculator':'',
//  'Wire Self Inductance Calculator':'',
//  'Wire Stripline Impedance Calculator':'',
//];

Map<String,String> cards = {
  '555 Timer Monostable Circuit Calculator':' computes output pulse width of a 555 timer monostable circuit',
  'Antenna Downtilt and Coverage Calculator':'',
  'Asymmetric Stripline Impedance Calculator':'',
  'Balanced Attenuator Calculator':'',
  'Bandpass Filter Calculator':'',
  'Bridged-Tee Attenuator Calculator':'',
  'Broadside Coupled Stripline Impedance Calculator':'',
  'Broadside Coupled Trace Inductance Calculator':'',
  'Capacitance Calculator':'',
  'Capacitance, Reactance, and Admittance Calculator':'',
  'Capacitor Charge and Time Constant Calculator':'',
  'Capacitor Impedance Calculator':'',
  'Coax Impedance Calculator':'',
  'Coax Inductance Calculator':'',
  'Coil Inductance Calculator':'',
  'Convert MCD to Lumens':'',
  'Edge Coupled Microstrip Impedance Calculator':'',
  'Edge Coupled Stripline Impedance Calculator':'',
  'Edge Coupled Trace Inductance Calculator':'',
  'EIRP Calculator':'',
  'Embedded Microstrip Impedance Calculator':'',
  'Flyback Switch Mode Regulator Calculator':'',
  'Free Space Path Loss Calculator':'',
  'Friis Transmission Calculator':'',
  'Heat Sink Calculator':'',
  'Inductance, Reactance, and Admittance Calculator':'',
  'Inverting Op-Amp Resistor Calculator':'',
  'L-Match Impedance Matching Circuits':'',
  'LED Resistor Calculator':'',
  'Link Budget Calculator':'',
  'Microstrip Crosstalk Calculator':'',
  'Microstrip Impedance Calculator':'',
  'Microstrip Inductance Calculator':'',
  'Microstrip Max Current Calculator':'',
  'Microstrip Patch Antenna Calculator':'',
  'Microstrip Trace Width Calculator':'',
  'Microstrip Wavelength Calculator':'',
  'N-Way Power Divider Calculator':'',
  'Noise Figure and Noise Temperature Calculator':'',
  'Noise Figure Calculator':'',
  'Non-Inverting Op-Amp Resistor Calculator':'',
  'Ohm’s Law Calculator':'',
  'Op-Amp Voltage and Gain Calculator':'',
  'Parallel Resistance Calculator':'',
  'Parallel Wire Inductance Calculator':'',
  'Peak to Peak Voltage Calculator (VP-P)':'',
  'Peak Voltage Calculator':'',
  'Pi Attenuator Calculator':'',
  'Pi-Match Impedance Matching Calculator':'',
  'Power Added Efficiency Calculator':'',
  'Power Density Calculator':'',
  'Radar Maximum Range Calculator':'',
  'Rectangle Loop Inductance Calculator':'',
  'Reflection Attenuator Calculator':'',
  'Resistance Calculator':'',
  'Resistor Color Code Calculator':'',
  'RF Power Conversion Calculator':'',
  'RF Power Ratio Conversion Calculator':'',
  'RMS Voltage Calculator':'',
  'Skin Depth Calculator':'',
  'Stepper Motor Calculator':'',
  'Stripline Crosstalk Calculator':'',
  'Stripline Max Current Calculator':'',
  'Stripline Trace Width Calculator':'',
  'Symmetric Stripline Impedance Calculator':'',
  'T-Match Impedance Matching Circuits':'',
  'T-Pad Attenuator Calculator':'',
  'Tank Circuit Resonance Calculator':'',
  'Temperature Converter':'',
  'Torque Conversion Calculator':'',
  'Trace Resistance Calculator':'',
  'Twisted-Pair Impedance Calculator':'',
  'Unit Conversion Calculator':'',
  'Voltage Divider Calculator':'',
  'VSWR  Return Loss Calculator':'',
  'Waveguide Calculator (Circular)':'',
  'Waveguide Calculator (Rectangular)':'',
  'Wavelength (TEM) Calculator':'',
  'Wire Loop Inductance Calculator':'',
  'Wire Microstrip Impedance Calculator':'',
  'Wire Over Plane Inductance Calculator':'',
  'Wire Self Inductance Calculator':'',
  'Wire Stripline Impedance Calculator':'',
};

//List<String> desc = [
//  ' computes output pulse width of a 555 timer monostable circuit':'',
//  ' determines antenna downtilt angle given heights of antennas and distance between them.':'',
//  ' computes characteristic impedance of an asymmetric stripline':'',
//  ' determines resistor values for a balanced attenuator':'',
//  ' calculates values of inductance, capacitance of an inductor and capacitor used in a Butterworth LC bandpass filter.':'',
//  ' determines values of resistors and to be used for a bridged-tee attenuator.':'',
//  ' computes characteristic impedance of a broadside coupled stripline.':'',
//  ' computes inductance of a broadside coupled trace.':'',
//  ' calculates capacitance of a capacitor based on its charge and voltage.':'',
//  ' solves capacitance, reactance, and admittance of a capacitor.':'',
//  ' computes capacitor charge time and energy, given supply voltage and added series resistance.':'',
//  ' calculates capacitor reactance for given capacitance value and signal frequency.':'',
//  ' calculates impedance of coaxial cable.':'',
//  ' computes inductance of coaxial cable.':'',
//  ' computes inductance of a coil.':'',
//  ' calculates luminous flux for LEDs where angle is known.':'',
//  ' calculates impedance of an edge coupled microstrip.':'',
//  ' computes impedance of an edge coupled stripline':'',
//  ' computes inductance of an edge coupled trace.':'',
//  ' computes Effective Isotropic Radiated Power (EIRP) of an antenna':'',
//  ' computes characteristic impedance of an embedded microstrip.':'',
//  ' computes parameters needed in design of a flyback switch mode regulator':'',
//  ' computes free space path loss between transmit and receive antennas.':'',
//  ' computes power received by an antenna using Friis formula':'',
//  ' determines maximum temperature a device can withstand':'',
//  ' calculates reactance and admittance of an inductor or inductance given reactance of an inductor':'',
//  ' determines bias and feedback of resistors for an inverting op-amp':'',
//  ' computes parameters needed to design a L-Match Impedance Circuit':'',
//  ' calculates LED resistance for single LED to know which resistor you should use.':'',
//  ' calculates power at receiver using link budget analysis.':'',
//  ' calculates cross-talk coefficient and coupled voltage for a microstrip.':'',
//  ' computes characteristic impedance of a microstrip.':'',
//  ' computes inductance of a microstrip etched on a PCB.':'',
//  ' solves maximum current a microstrip can handle.':'',
//  ' calculates dimensions of microstrip patch antenna given desired operating frequency.':'',
//  ' computes trace width of a microstrip':'',
//  ' calculates guided wavelength inside a microstrip.':'',
//  ' determines total path loss provided by an RF n-way power splitter.':'',
//  ' computes noise figure and noise temperature in a system':'',
//  ' calculate noise figure of cascaded amplifiers':'',
//  ' determines bias and feedback of resistors for a non-inverting Op-Amp':'',
//  ' calculates circuit parameters using Ohms Law':'',
//  ' computes gain and output voltage of an operational amplifier':'',
//  ' calculates total resistance of resistors in parallel with ease!':'',
//  ' calculates inductance of two parallel wires':'',
//  ' shows peak-to-peak voltage (VP-P) value from peak voltage, RMS voltage, or average voltage.':'',
//  ' calculates peak voltage values from peak-to-peak voltage, RMS voltage, or average voltage.':'',
//  ' determines values of resistors R1 and R2 to be used for a Pi Attenuator.':'',
//  ' computes parameters required to design a Pi-Match Impedance Circuit':'',
//  ' computes power-added efficiency (PAE) of an amplifier':'',
//  ' calculates power density of an antenna':'',
//  ' calculates maximum distance (range) that a radar can detect':'',
//  ' computes inductance of a rectangle loop.':'',
//  ' calculates value of resistance R1 in a reflection attenuator.':'',
//  ' calculates resistivity of a component based on its resistance value, length, and cross-sectional area.':'',
//  ' reads resistor color code values':'',
//  ' converts RF power from watts to decibels and vice versa':'',
//  ' converts power ratios to decibel':'',
//  ' calculates RMS Voltage value from either peak voltage, peak-to-peak voltage, or average voltage.':'',
//  ' calculates skin depth based on conductive material being used and frequency of signal.':'',
//  ' calculates maximum speed, minimum time per step and maximum power of a stepper motor':'',
//  ' calculates cross-talk coefficient and coupled voltage for a stripline':'',
//  ' calculates maximum current that a stripline can handle':'',
//  ' calculates trace width of a stripline based on maximum current rating':'',
//  ' computes characteristic impedance of a symmetric stripline.':'',
//  ' computes values to be used in a T-match Impedance Circuit':'',
//  ' determines values of resistors R1 and R2 to be used for a T-pad attenuator.':'',
//  ' computes resonant frequency of a tank circuit':'',
//  ' converts between Celsius, Fahrenheit and Kelvin':'',
//  ' converts between units of torque':'',
//  ' determines resistance of a microstrip trace':'',
//  ' calculates characteristic impedance of a twisted-pair cable':'',
//  ' converts to and from different units of length, weight, power, temperature and torque':'',
//  ' is used to create a voltage less than or equal to input voltage.':'',
//  ' computes VSWR, reflection coefficient, return loss and matching loss in a transmission line':'',
//  ' calculates cutoff frequency of a circular waveguide':'',
//  ' calculates cutoff frequency of a rectangular waveguide':'',
//  ' determines wavelength of a signal given frequency and dielectric constant.':'',
//  ' computes inductance of a wire loop.':'',
//  ' calculates impedance of a wire microstrip.':'',
//  ' computes inductance of a wire-over-plane setup.':'',
//  ' computes inductance of a length of wire.':'',
//  ' computes impedance of a wire stripline.':'',
//];
//
//List<String> thumbnail = [
//  '':'',
//];
